# Generated by Django 4.1.5 on 2023-01-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=250)),
                ('current_status', models.CharField(max_length=250)),
                ('current_location', models.CharField(max_length=250)),
                ('amount_paid', models.CharField(max_length=250)),
                ('schedule_delivery', models.CharField(max_length=250)),
                ('origin', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('services', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('weight', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('date_sent', models.CharField(max_length=250)),
                ('expected_delivery_date', models.CharField(max_length=250)),
                ('comments', models.CharField(max_length=250)),
                ('sender_name', models.CharField(max_length=250)),
                ('sender_country', models.CharField(max_length=250)),
                ('consignee_name', models.CharField(max_length=250)),
                ('consignee_address', models.CharField(max_length=250)),
                ('consignee_country', models.CharField(max_length=250)),
            ],
        ),
    ]
