# Generated by Django 4.1.5 on 2023-01-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_amount_paid_alter_product_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tracking_code',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
